spring:
  application:
    name:stock
  datasource:
    url:jdbc:postgresql://localhost:5432/stock
    username:postgres
    password:663733
    driverClassName:org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
        showSql:true
        formatSql:true
      hbm2ddl:
        auto=update